#!/bin/bash 

# send a mail to the the team when a ping to a server fails

function mailDevopsTeamOnDownTime {
# teams will take in team emails
  team=("teammember1@gmail.com" "teammemeber2gmail.com"  "teammemeber3gmail.com")

  for i in $@
  do
  # echo first $i
  ping -c 1 $i &> /dev/null
  
    if [ $? -ne 0 ]; then
      for t in ${team[@]}; 
      do
      # mail 
      # -c cc
      # -b bcc
      echo $i $t
      echo  "`date`: ping failed. $i host is down" | mail -s "$i host is down" $t
      done 
    fi
  done
}

mailDevopsTeamOnDownTime google.com yahoo.com 192.168.2.2 192.1.1.1 192.1.1.6774
